#array creation

In [2]:
import numpy as np

In [3]:
arr1=np.zeros([3,4])
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
arr2=np.ones([2,3])
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arr3=np.full([3,4],6)
print(arr3)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [6]:
arr4=np.random.random([3,4])
print(arr4)

[[0.89619126 0.20575671 0.77101318 0.5640802 ]
 [0.03960268 0.18692077 0.02311042 0.99867786]
 [0.3175095  0.00509    0.11977505 0.29433257]]


In [10]:
arr5=np.arange(0,9,2)
print(arr5)

[0 2 4 6 8]


#vector,matrix,tensor

In [14]:
vector = np.array([1,2,3])
print("vector:\n",vector)

matrix=np.array([[1,2,3],[5,6,7]])
print("matrix:\n",matrix)

tensor=np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print("tensor:\n",tensor)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [5 6 7]]
tensor:
 [[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
