# array reshaping

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("original array : ",arr)

reshaped =arr.reshape(3,3)
print("\n reshaped : ",reshaped)

flattend=reshaped.flatten()
print("\n flattend: ",flattend)

raveled = reshaped.ravel()
print("\n raveled : ",raveled)

transpose = reshaped.T
print("\n transpose : ",transpose)


original array :  [1 2 3 4 5 6 7 8 9]

 reshaped :  [[1 2 3]
 [4 5 6]
 [7 8 9]]

 flattend:  [1 2 3 4 5 6 7 8 9]

 raveled :  [1 2 3 4 5 6 7 8 9]

 transpose :  [[1 4 7]
 [2 5 8]
 [3 6 9]]
