# array slicing in numpy

In [1]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:])
print(arr[:-1])
print(arr[-1:])
print(arr[:])
print(arr[2:-2])
print(arr[1:-1:2])


[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7]
[8]
[1 2 3 4 5 6 7 8]
[3 4 5 6]
[2 4 6]


In [8]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element: ",arr_2d[1,1])
print("specific element: ",arr_2d[2,0])
print("entire row:",arr_2d[2,])
print("entire column:",arr_2d[:,0])

specific element:  5
specific element:  7
entire row: [7 8 9]
entire column: [1 4 7]
