#sort array 

In [2]:
import numpy as np

In [3]:
unsorted = np.array([9,3,8,1,9,2,0])
print("soring an array :",np.sort(unsorted))
print("soring an array :",np.sort(unsorted[2:-2]))
print("soring an array :",np.sort(unsorted[0:]))

 

soring an array : [0 1 2 3 8 9 9]
soring an array : [1 8 9]
soring an array : [0 1 2 3 8 9 9]


In [10]:
unsorted_2d = np.array([[3,2,1],
                        [5,6,4],
                        [8,3,7]])

print("sorted 2d array :\n",np.sort(unsorted_2d)) #by default it sort by row 
print("sorted 2d array by column :\n",np.sort(unsorted_2d,axis=0))
print("sorted 2d array by row:\n",np.sort(unsorted_2d,axis=1))


sorted 2d array :
 [[1 2 3]
 [4 5 6]
 [3 7 8]]
sorted 2d array by column :
 [[3 2 1]
 [5 3 4]
 [8 6 7]]
sorted 2d array by row:
 [[1 2 3]
 [4 5 6]
 [3 7 8]]
