#fancy indexing

In [16]:
import numpy as np
number = np.array([1,2,3,4,5,6,7,8,9,10])

In [17]:
indicies = [0,4,-1]
print(number[indicies])

[ 1  5 10]


###np.where()

In [19]:
where_result = np.where(number>5)
print(where_result)
print(number[where_result])

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [23]:
condition_array =  np.where(number%2==0 , "Even","Odd")
print( number)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]
['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']
