In [1]:
import numpy as np

### adding two array

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1 , arr2))
print("addition of two array :",combined)

addition of two array : [1 2 3 4 5 6]


###deletion

In [ ]:
deletion = np.delete(combined,2)
print("before deletion",combined)
print("after deletion",deletion)

before deletion [1 2 3 4 5 6]
after deletion [1 2 4 5 6]


###compatibility (check shape of both array)

In [15]:
array1 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
array2 = np.array([[2,1,3],
                  [4,5,6],
                  [7,5,8]])
print("compatibility shape :",array1.shape==array2.shape)

compatibility shape : True


###Vstack (This function is particularly useful for combining arrays row wise)

In [19]:
arr_3 = np.array([[1,2],
                  [3,4]])
new_row = [5,6]
final_array = np.vstack((arr_3,new_row))
print("before :\n",arr_3)
print("after :\n",final_array)

before :
 [[1 2]
 [3 4]]
after :
 [[1 2]
 [3 4]
 [5 6]]


###hstack (This function is particularly useful for combining arrays column  wise)

In [18]:
arr_4 = np.array([[1,2],
                  [3,4]])
new_column = [[5],[6]]
result = np.hstack((arr_4,new_column))
print("before :\n",arr_4)
print("after :\n",result)

before :
 [[1 2]
 [3 4]]
after :
 [[1 2 5]
 [3 4 6]]
